name: Format Message
description: Take message JSON and format them for the corresponding

inputs:
  SPELL_MESSAGE:
    description: Unformatted spell check message
    required: true

outputs:
  FORMATTED_MESSAGE:
    description: formatted message for desired communication channel
    value: ${{ steps.format_msg.outputs.FORMATTED_MESSAGE }}

runs:
  using: "composite"
  steps:
    - name: 🔨 Format Notification
      shell: bash
      id: format_msg
      run: |
        cd ${{ github.action_path }}
        yarn
        yarn format
      env:
        SPELL_MESSAGE: ${{ inputs.SPELL_MESSAGE }}
