name: spell check
description: using Cspell to check the spelling from the input DIFF files

inputs:
  DIFF:
    description: List of space delimted files from pull request to be checked
    required: true
outputs:
  SPELL_ERRORS:
    description:
    value: ${{ steps.spellcheck.outputs.CSPELL_ERRORS }}

runs:
  using: composite
  steps:
    - name: Run Spell Check
      id: spellcheck
      shell: bash
      if: ${{ inputs.DIFF }} != ''
      run: |
        cd ${{ github.action_path }}
        yarn
        yarn spell
      env:
        DIFF: ${{ inputs.DIFF }}
        GITHUB_ORG: ${{ inputs.GITHUB_ORG }}
        GH_TOKEN: ${{ inputs.GH_TOKEN }}
# yarn add cspell
# CSPELL_ERRORS=$(cspell lint --no-exit-code --config ${{ github.action_path }}/.cspell.json ${{ inputs.DIFF }})
# echo "CSPELL_ERRORS=$(CSPELL_ERRORS)" >> $GITHUB_OUTPUT

