name: Send Discord Message Via Webhook
on:
  workflow_call:
    inputs:
      MESSAGE:
        required: true
        type: string
      color:
        required: false
        type: string
        default: "0"
      BOT_NAME:
        required: false
        type: string
        default: "GitHub Actions"
      avatar_url:
        required: false
        type: string

jobs:
  send-message:
    runs-on: ubuntu-latest
    steps:
      - name: 📩 Send Discord Message
        uses: alcash55/ac-composite-actions/notifications/discord-messages@main
        with:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          MESSAGE: ${{ inputs.MESSAGE }}
          BOT_NAME: ${{ inputs.BOT_NAME }}
          AVATAR_URL: ${{ inputs.AVATAR_URL }}
