name: Test resume analysis

on:
  pull_request:
    branches:
      - "main"

jobs:
  test-analysis:
    uses: alcash55/ac-composite-actions/.github/workflows/resume-analysis.yml@main
    with:
      ORG: "${{ github.repository }}"
      BRANCH: "${{ github.ref }}"
      PR_NUMBER: ${{ github.event.number }}
      GH_TOKEN: "${{ github.token }}"
